### ISSUE TITLE
Update for 1.5.0

### ISSUE THREAD

**Issue by EhsanKia** [imthe666st/ACNH#4]
Hello, any chance we could have a 1.5.0 update.

Otherwise, if a script is used to generate this data from the raw data, it would be nice if we could have those scripts so in the future anyone can generate/update this repo.

**Comment by phecdaDia** [comment]
I was a bit busy, I'm sorry, I'm currently getting the 1.5 data and maybe finally getting myself to turn everything into a sharable script. The current one is mostly botched together so I didn't really want to share it because it's just.. bad.

Will upload the 1.5 stuff in a bit, had to fix my modded switch first.

**Comment by phecdaDia** [comment]
Uploaded 1.5 stuff, but something went wrong with the diff and tbh I don't know how to fix that :c 
Will make a new issue for releasing a sharable script and try to work on it soon when I find some times.

**Comment by EhsanKia** [comment]
Haha no worries, thank you for the update :)

**Comment by EhsanKia** [comment]
For, what it's worth, the line endings is what broke the diff. old one has unix endings \n, new ones have windows \r\n ending

**Comment by phecdaDia** [comment]
Ahh.. that's probably because I had to reinstall everything a while back... It must have changed the automatic line endings in the json library which I used to turn a python dictionary to a json object..
Oh well, not that big of a problem... (I hope (I'm sorry for every service I just broke))

**Comment by EhsanKia** [comment]
It's probably the git setting rather than python actually. Maybe `git config --global core.autocrlf true` although in this case making it local might actually help in case of re-installs.
