### ISSUE TITLE
Add a script to generate item ids yourself

### ISSUE THREAD

**Issue by phecdaDia** [imthe666st/ACNH#5]
The current script used is messy and just botched together, a sharable version would allow people to generate the item IDs themselves provided they can dump the game files required.

**Comment by phecdaDia** [comment]
Added script to dump item IDs.

**Comment by sir1st** [comment]
can you make a short introduction for how to get the ItemParam.bcsv file? cause it's hard to find where should i start.. Really Appreciate for that

**Comment by phecdaDia** [comment]
ItemParam.bcsv can be found in romfs://Bcsv/ 
The String_XXxx.sarc.zs files can be found in romfs://Message/

Neither of those files will be distributed, use tools like NxDumptool (<https://github.com/DarkMatterCore/nxdumptool>) to dump the individual files and then transfer them to your computer, either by physically plugging in your SD card into an SD card reader or using FTP with one of the various homebrew programs available for the Switch.

**Comment by sir1st** [comment]
thanks, after change some codes and install the python packages, it works on my computer!
