### ISSUE TITLE
hello,when i use make_item_list.py.Its only extract Bcsv_out floder,and doesn't make item_ids.

### ISSUE THREAD

**Issue by illyasever-lol** [imthe666st/ACNH#8]
my conputer is windows 10 python is 3.8.5
I put all files on D:\ACNH-master\scripts\extract_items.
and take ItemParam.bcsv on D:\ACNH-master\scripts\extract_items\Bcsv
all scar.zs on D:\ACNH-master\scripts\extract_items\Message
at last i double-click make_item_list.py，its only extract Bcsv_out floder,and doesn't make item_ids.
so,its my format or directory wrong or others?
Can your teacher me how to fix it.
thanks.

**Comment by phecdaDia** [comment]
Please provide the output of the script.  
I'm currently also dumping the 1.8.0 item ids, going to update in a bit.

**Comment by phecdaDia** [comment]
Seems like the usage for `zstandard` changed a bit which broke the script. I'm going to push an update in a second.

**Comment by phecdaDia** [comment]
Updated the script and it now runs flawlessly again on my end. Please try the new update.

**Comment by illyasever-lol** [comment]
Thank you for your reply!
I test new script.
Put them in D:\ACNH-master\scripts\extract_items,and double-click make_item_list.py.
I saw when Bcsv_out end,waring" file not found error: dont find message_unpack\\language".
In the end,make_item_list.py run over,item_ids floder is empty.
Whats wrong whit me.

**Comment by phecdaDia** [comment]
Please provide the entire output of the script. 
Do not just double click it, but rather start a CMD or Powershell and execute the script with `python3 make_item_list.py`. Since you're on Windows simply append `> log.txt` to receive a text file, if that's more convenient. 

The script is also simply calling other scripts using `py`, if this alias doesn't exist for you simply replace them with your python3 alias.

**Comment by illyasever-lol** [comment]
I test CMD execute the script.
It say
C:\Users\Administrator>py "D:\ACNH-master\scripts\extract_items\make_item_list.py"
Dumping Item IDs
Unable to find ItemParam.bcsv in Bcsv directory!
Im sure i put all bcsv on D:\ACNH-master\scripts\extract_items\Bcsv floder.
Sorry for the ask,waste your times.

**Comment by illyasever-lol** [comment]
when i cd path run
it run logo

D:\>cd ACNH-master

D:\ACNH-master>cd scripts

D:\ACNH-master\scripts>cd extract_items

D:\ACNH-master\scripts\extract_items>py make_item_list.py
Dumping Item IDs
Found the following languages:  ['CNzh', 'EUde', 'EUen', 'EUes', 'EUfr', 'EUit', 'EUnl', 'EUru', 'JPja', 'KRko', 'TWzh', 'USen', 'USes', 'USfr']
All required files seem to be present, proceeding.
Building specs
Dumping bcsv
Extracting Files from sarc.zs
Traceback (most recent call last):
  File "extract_sarc_zs.py", line 2, in <module>
    import sarc
ModuleNotFoundError: No module named 'sarc'
Traceback (most recent call last):
  File "dump_items.py", line 34, in <module>
    item_msbts = load_msbt(os.path.join(base_path, 'Item'))
  File "dump_items.py", line 32, in <lambda>
    load_msbt = lambda path: [(f, Msbt.create_from_file(os.path.join(path, f))) for f in os.listdir(path) if f.endswith('.msbt')]
FileNotFoundError: [WinError 3] cant find path。: 'Message_unpack\\String_CNzh\\Item'
Finished dumping items for CNzh
Traceback (most recent call last):
  File "dump_items.py", line 34, in <module>
    item_msbts = load_msbt(os.path.join(base_path, 'Item'))
  File "dump_items.py", line 32, in <lambda>
    load_msbt = lambda path: [(f, Msbt.create_from_file(os.path.join(path, f))) for f in os.listdir(path) if f.endswith('.msbt')]
FileNotFoundError: [WinError 3] cant find path。: 'Message_unpack\\String_EUde\\Item'
Finished dumping items for EUde
Traceback (most recent call last):
  File "dump_items.py", line 34, in <module>
    item_msbts = load_msbt(os.path.join(base_path, 'Item'))
  File "dump_items.py", line 32, in <lambda>
    load_msbt = lambda path: [(f, Msbt.create_from_file(os.path.join(path, f))) for f in os.listdir(path) if f.endswith('.msbt')]
FileNotFoundError: [WinError 3] cant find path。: 'Message_unpack\\String_EUen\\Item'
Finished dumping items for EUen
Traceback (most recent call last):
  File "dump_items.py", line 34, in <module>
    item_msbts = load_msbt(os.path.join(base_path, 'Item'))
  File "dump_items.py", line 32, in <lambda>
    load_msbt = lambda path: [(f, Msbt.create_from_file(os.path.join(path, f))) for f in os.listdir(path) if f.endswith('.msbt')]
FileNotFoundError: [WinError 3] cant find path。: 'Message_unpack\\String_EUes\\Item'
Finished dumping items for EUes
Traceback (most recent call last):
  File "dump_items.py", line 34, in <module>
    item_msbts = load_msbt(os.path.join(base_path, 'Item'))
  File "dump_items.py", line 32, in <lambda>
    load_msbt = lambda path: [(f, Msbt.create_from_file(os.path.join(path, f))) for f in os.listdir(path) if f.endswith('.msbt')]
FileNotFoundError: [WinError 3] cant find path。: 'Message_unpack\\String_EUfr\\Item'
Finished dumping items for EUfr
Traceback (most recent call last):
  File "dump_items.py", line 34, in <module>
    item_msbts = load_msbt(os.path.join(base_path, 'Item'))
  File "dump_items.py", line 32, in <lambda>
    load_msbt = lambda path: [(f, Msbt.create_from_file(os.path.join(path, f))) for f in os.listdir(path) if f.endswith('.msbt')]
FileNotFoundError: [WinError 3] cant find path。: 'Message_unpack\\String_EUit\\Item'
Finished dumping items for EUit
Traceback (most recent call last):
  File "dump_items.py", line 34, in <module>
    item_msbts = load_msbt(os.path.join(base_path, 'Item'))
  File "dump_items.py", line 32, in <lambda>
    load_msbt = lambda path: [(f, Msbt.create_from_file(os.path.join(path, f))) for f in os.listdir(path) if f.endswith('.msbt')]
FileNotFoundError: [WinError 3] cant find path。: 'Message_unpack\\String_EUnl\\Item'
Finished dumping items for EUnl
Traceback (most recent call last):
  File "dump_items.py", line 34, in <module>
    item_msbts = load_msbt(os.path.join(base_path, 'Item'))
  File "dump_items.py", line 32, in <lambda>
    load_msbt = lambda path: [(f, Msbt.create_from_file(os.path.join(path, f))) for f in os.listdir(path) if f.endswith('.msbt')]
FileNotFoundError: [WinError 3] cant find path。: 'Message_unpack\\String_EUru\\Item'
Finished dumping items for EUru
Traceback (most recent call last):
  File "dump_items.py", line 34, in <module>
    item_msbts = load_msbt(os.path.join(base_path, 'Item'))
  File "dump_items.py", line 32, in <lambda>
    load_msbt = lambda path: [(f, Msbt.create_from_file(os.path.join(path, f))) for f in os.listdir(path) if f.endswith('.msbt')]
FileNotFoundError: [WinError 3] cant find path。: 'Message_unpack\\String_JPja\\Item'
Finished dumping items for JPja
Traceback (most recent call last):
  File "dump_items.py", line 34, in <module>
    item_msbts = load_msbt(os.path.join(base_path, 'Item'))
  File "dump_items.py", line 32, in <lambda>
    load_msbt = lambda path: [(f, Msbt.create_from_file(os.path.join(path, f))) for f in os.listdir(path) if f.endswith('.msbt')]
FileNotFoundError: [WinError 3] cant find path。: 'Message_unpack\\String_KRko\\Item'
Finished dumping items for KRko
Traceback (most recent call last):
  File "dump_items.py", line 34, in <module>
    item_msbts = load_msbt(os.path.join(base_path, 'Item'))
  File "dump_items.py", line 32, in <lambda>
    load_msbt = lambda path: [(f, Msbt.create_from_file(os.path.join(path, f))) for f in os.listdir(path) if f.endswith('.msbt')]
FileNotFoundError: [WinError 3] cant find path。: 'Message_unpack\\String_TWzh\\Item'
Finished dumping items for TWzh
Traceback (most recent call last):
  File "dump_items.py", line 34, in <module>
    item_msbts = load_msbt(os.path.join(base_path, 'Item'))
  File "dump_items.py", line 32, in <lambda>
    load_msbt = lambda path: [(f, Msbt.create_from_file(os.path.join(path, f))) for f in os.listdir(path) if f.endswith('.msbt')]
FileNotFoundError: [WinError 3] cant find path。: 'Message_unpack\\String_USen\\Item'
Finished dumping items for USen
Traceback (most recent call last):
  File "dump_items.py", line 34, in <module>
    item_msbts = load_msbt(os.path.join(base_path, 'Item'))
  File "dump_items.py", line 32, in <lambda>
    load_msbt = lambda path: [(f, Msbt.create_from_file(os.path.join(path, f))) for f in os.listdir(path) if f.endswith('.msbt')]
FileNotFoundError: [WinError 3] cant find path。: 'Message_unpack\\String_USes\\Item'
Finished dumping items for USes
Traceback (most recent call last):
  File "dump_items.py", line 34, in <module>
    item_msbts = load_msbt(os.path.join(base_path, 'Item'))
  File "dump_items.py", line 32, in <lambda>
    load_msbt = lambda path: [(f, Msbt.create_from_file(os.path.join(path, f))) for f in os.listdir(path) if f.endswith('.msbt')]
FileNotFoundError: [WinError 3] cant find path。: 'Message_unpack\\String_USfr\\Item'
Finished dumping items for USfr
end

**Comment by phecdaDia** [comment]
> ModuleNotFoundError: No module named 'sarc'

Please install the python modules which are required and detailed in the readme.

**Comment by illyasever-lol** [comment]
Its done!Thanks a lot!
I use cmd to run
C:\Users\Administrator>"C:\Program Files (x86)\python3\Scripts\pip3.exe" install sarc
C:\Users\Administrator>"C:\Program Files (x86)\python3\Scripts\pip3.exe" install zstandard
C:\Users\Administrator>"C:\Program Files (x86)\python3\Scripts\pip3.exe" install zlib
And last run d:\ACNH-master\scripts\extract_items>py make_item_list.py
Extracting Files from sarc.zs
Finished extracting Message\String_CNzh.sarc.zs successfully
Finished extracting Message\String_EUde.sarc.zs successfully
Finished extracting Message\String_EUen.sarc.zs successfully
Finished extracting Message\String_EUes.sarc.zs successfully
Finished extracting Message\String_EUfr.sarc.zs successfully
Finished extracting Message\String_EUit.sarc.zs successfully
Finished extracting Message\String_EUnl.sarc.zs successfully
Finished extracting Message\String_EUru.sarc.zs successfully
Finished extracting Message\String_JPja.sarc.zs successfully
Finished extracting Message\String_KRko.sarc.zs successfully
Finished extracting Message\String_TWzh.sarc.zs successfully
Finished extracting Message\String_USen.sarc.zs successfully
Finished extracting Message\String_USes.sarc.zs successfully
Finished extracting Message\String_USfr.sarc.zs successfully
Finished dumping items for CNzh
Finished dumping items for EUde
Finished dumping items for EUen
Finished dumping items for EUes
Finished dumping items for EUfr
Finished dumping items for EUit
Finished dumping items for EUnl
Finished dumping items for EUru
Finished dumping items for JPja
Finished dumping items for KRko
Finished dumping items for TWzh
Finished dumping items for USen
Finished dumping items for USes
Finished dumping items for USfr

Thanks for teacher me.I learn some new knowledge！
